### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by xgraza**
hey hey hey, guess what,

YOURE NOT GETTING A FUCKING UNBAN.

you fucking raided our server, are you fucking kidding? you put a knife by 2D's name as to threaten him? are you fucking shitting me? you're going to threatening over a FUCKING CLIENT MOD BAN YOU. you can go FUCK yourself before you get an unban. if you think your skiddish fucking C# bot raiders is gonna make us unban you youre fucking mistaken

thanks ~!

gavin, aesthetical

### CODE REVIEW

**Comment by chanios** [comment]
huh knife by 2D's name as to threaten them. no I think it for joke :c. so sorry about that

**Comment by xgraza** [comment]
a joke. a joke you say. please tell me youre a comedian

**Comment by xgraza** [comment]
like bro you realease, you could've gotten your unban by DMing me or 2D after your ban, most likely me as 2D doesn't accept frs as much that i know of.

like you resort to raiding??!?!?!

**Comment by chanios** [comment]
He ban &  unfriend me so what how the other way to contact him

**Comment by xgraza** [comment]
LMOA WHATH ARE YOUF UCKING KDISINSIOSDNUANFIUFNIAFUNISU

bro. if you read the rules you can legit dm **me** or 2D. regardless, you fucking raid a discord server?

**Comment by chanios** [comment]
+ I am not raid

**Comment by chanios** [comment]
I am not raidder I just want My bot to be add on the list. that it. and you guy ban me

**Pull request merged**
